## Programming Assignment No 08

#### Q1.Write a Python Program to Add Two Matrices?

In [14]:
import numpy as np 

arr1 = np.array([[1,2,3],[3,4,5]])
arr2 = np.array([[5,2,4],[8,7,4]])

print(arr1 + arr2)

[[ 6  4  7]
 [11 11  9]]


#### Q2.Write a Python Program to Multiply Two Matrices?

In [21]:
import numpy as np 

arr1 = np.array([[1,2,3],[3,4,5]])
arr2 = np.array([[5,2,4],[8,7,4]])

print("Element wise multiplication : ")
print(arr1*arr2)
print()
print("Dot product : ")
# Dot product 
print(np.dot(arr1,arr2.reshape(3,2)))

Element wise multiplication : 
[[ 5  4 12]
 [24 28 20]]

Dot product : 
[[34 30]
 [66 58]]


#### Q3.Write a Python Program to Transpose a Matrix?

In [24]:
import numpy as np 

arr1 = arr1 = np.array([[1,2,3],[3,4,5]])
print(' Array Before transpose : ')
print(arr1)
print()

arr3 = np.transpose(arr1)
print("Array after transpose : ")
print(arr3)

 Array Before transpose : 
[[1 2 3]
 [3 4 5]]

Array after transpose : 
[[1 3]
 [2 4]
 [3 5]]


#### Q4.Write a Python Program to Sort Words in Alphabetic Order?

In [31]:
word = ["Myself","Vinayak","I","Have","Enrolled","In","FSDS","Programme"]
word.sort()
print(word)

['Enrolled', 'FSDS', 'Have', 'I', 'In', 'Myself', 'Programme', 'Vinayak']


#### Q5.Write a Python Program to Remove Punctuation From a String?

In [39]:
string = "Good Morning!"

string = string.replace("!","")
print(string)

Good Morning
